### ISSUE TITLE
Récupérer la clé IFTTT

### ISSUE THREAD

**Issue by mikebzh44** [Aymkdn/assistant-ifttt#1]
Salut.

Je tente de mettre en place ta solution pour piloter ma Freebox via mon Google Home mini mais je ne comprends pas ta phrase : 

"Se rendre dans le maker WebHooks de IFTTT et le configurer. Une clé (key) vous sera alors donnée (qui ressemble à dph-Wyhz1Zxlw89WZchMAV)."

Si je vais sur l'URL, https://ifttt.com/maker_webhooks, j'ai ça :

https://imgur.com/hQagmCo

Comment et où on récupère notre clé ?

Si ça peut aider, j'ai déjà des webhooks de créés car j'utilise IFTTT pour piloter mon Jeedom.

Merci de ton aider.

**Comment by Aymkdn** [comment]
Tu n'as pas besoin du plugin IFTTT pour piloter la Freebox.

Si tu souhaites quand même un jour utiliser ce plugin, il faut aller dans **Settings** (https://ifttt.com/services/maker_webhooks/settings) et là tu devrais voir ton code : 

![capture](https://user-images.githubusercontent.com/946315/33517365-63c50b82-d783-11e7-8c25-c041dff04d15.png)
